### PR TITLE
fix: Render koopa sprites with transparent background

### LINKED ISSUE #84: Koopas not rendering with transparent background
**Description**
Koopa sprites are being rendered with a non-transparent background:

koopa_non_transparent

**Acceptance Criteria**
Convert sprites to render with a transparent background.

### PR DESCRIPTION
**Pull request by mitruly**
**Description**
Updated koopa sprites to a transparent background. The current koopas render with a non-transparent background:
koopa_non_transparent

Screen capture of game rendered with koopa sprites on a transparent background:
koopa_transparent

Fixes #84.

### CODE REVIEW

**Comment by mx0c** [comment]
Hey, could you ellaborate what you changed in the png ? Because unfortunately this results in weird lookin koopas for me. 
image

Also the problem you stated isnt there for me. Maybe this is a MacOS or pygame version related issue ?

**Comment by thcheetah777** [comment]
I don't have that problem either

**Comment by mitruly** [comment]
@mx0c I removed the background (which appears as a teal tint) for me. I can dig into this a bit more if both of you are not experiencing this issue.

Are you both running Linux or Windows?

**Comment by thcheetah777** [comment]
I am running on a Windows 7

**Comment by mx0c** [comment]
win 10

**Pull request merged**
