### PR TITLE
Jump

### PR DESCRIPTION
**Pull request by Perseus-Perry**
Jump system reworked.
You can now specify jump height and jump speed 
This allows for fine tuning and getting a better feel for mario's jump.

### CODE REVIEW

**Comment by Perseus-Perry** [comment]
Also please remove the print statement in jump.py
Forgot to remove it.

**Comment by mx0c** [comment]
could you explain a bit what you changed and especially why?

**Comment by Perseus-Perry** [comment]
well in the original game mario takes 18 frames to reach to the top of his jump and 10 frames to fall back down. With the earlier jump system you would decrease mario's jump velocity to make him  jump slower and increase him fall down speed to make him fall faster like in the actual game. but then that would impact his jump height. my changes allow you to specify a jump height and jump speed and that ensures that you can change the jump speed without impacting the height mario reaches.
One thing to note : If the jump velocity is too high then mario bypasses the jump height limit. but that's not a problem except in the most extreme cases.

**Comment by mx0c** [comment]
you seem to have a good understanding on how the actual game works. If you want, you could improve the movement of mario so that it feels more like in the original game.

**Comment by Perseus-Perry** [comment]
yeah im working on that but i think it would be a good idea to maybe set up a discord server or something so as to you know...contact with other collaborators .

**Pull request merged**
