### PR TITLE
A few refactorings

### PR DESCRIPTION
**Pull request by Morinator**
All of these refactorings can be viewed totally independently.

The only thing I'm a bit unsure about is the replacement of _int()_ in _EntityBase_. 
int() rounds towards 0, i.e. upwards for negative numbers. The integer-division operator "//" **always** rounds down.
From my understanding, this makes no difference, as the inputs are always non-negative anyways.

### CODE REVIEW

**Comment by mx0c** [comment]
Overall good changes, but not sure if f-strings should be used because they are only available in Python <= 3.6. If you want you can  PR your other changes. :)

**Comment by Morinator** [comment]
I assume you mean >= 3.6?

How would you best PR only the other changes? Manually undo the changes for f-Strings and then PR again? Or is there a smarter way?

**Comment by mx0c** [comment]
hmm you could make a new branch and then cherry pick the commits you want. Not sure if its the fastest method though.

**Comment by Morinator** [comment]
Ok I did it manually. It's not shown in this conversation apparently, but the new commit for it is listed under "Commits" for this PR.

**Pull request merged**
