### PR TITLE
Standalone compiler fix #18

### LINKED ISSUE #18: Add windows standalone build
howto: https://www.pygame.org/wiki/Pygame2exe

### PR DESCRIPTION
**Pull request by tyoungNIO**
I found a much simpler,and python3 compatible, way to do this, but I don't have a fully setup 3.4 environment to finish testing this with (3.5+ will not work). Compiling is easy, run `python pygame2exe.py py2exe` from the repo root, and the newly created `dist` dir will have your `exe` in it.

Resolves #18

### CODE REVIEW

**Comment by tyoungNIO** [comment]
Almost forgot, I followed this tutorial: http://www.py2exe.org/index.cgi/Tutorial

And here is a stackoverflow thread answering why this doesn't work with py3.5+ https://stackoverflow.com/questions/41578808/python-indexerror-tuple-index-out-of-range-when-using-py2exe

**Comment by mx0c** [comment]
Did the executable work for you after building? I had to copy the neccessary runtime files into the dist folder (sprites/levels etc.). Would be great if you could resolve this issue :)

**Comment by tyoungNIO** [comment]
Interesting, I'll have to install python 3.4 and try it out. Certain DLLs etc are probably unavoidable, but everything should have been included in that folder.

**Comment by mx0c** [comment]
Already fixed it. You have to declare the neccessary folders/files with the data_files argument. Thanks for your PR anyways :)

**Pull request closed without merging**
